apiVersion: v2
name: traefik
description: Traefik ingress controller for k3s homelab cluster
type: application
version: 1.0.0
appVersion: "3.2.3"

dependencies:
  - name: traefik
    version: "33.2.1"
    repository: https://traefik.github.io/charts
