---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apache.fullname" . }}-html
  labels:
    {{- include "apache.labels" . | nindent 4 }}
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
     <meta charset="utf-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>{{ .Values.projectName }}.com</title>
     <link rel="icon" href="favicon.ico" type="image/png" />
     <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap" rel="stylesheet">
     <link href="https://use.fontawesome.com/releases/v6.7.2/css/all.css" rel="stylesheet">
     <link rel="stylesheet" href="css/reset.css">
     <link rel="stylesheet" href="css/styles.css">
     <link rel="stylesheet" href="css/theme.css">
    </head>
    <body>
     <main>
     <div class="container">
       <div class="img-sm">
         <img src="logo.png" alt="{{ .Values.projectName }} Logo">
       </div>
       <h1 class="site-title">{{ .Values.projectName }}</h1>
       <div class="icons-apps">
         <a href="/" class="nav-link">
           <i class="fas fa-home" aria-hidden="true"></i>
           <span>Home</span>
         </a>
         <a href="https://{{ .Values.homerDomain }}/" class="nav-link">
           <i class="fas fa-gauge-high" aria-hidden="true"></i>
           <span>Dashboard</span>
         </a>
         <a href="https://{{ .Values.autheliaDomain }}/" class="nav-link">
           <i class="fas fa-user" aria-hidden="true"></i>
           <span>Login</span>
         </a>
         <a href="/privacy" class="nav-link">
           <i class="fas fa-user-shield" aria-hidden="true"></i>
           <span>Privacy</span>
         </a>
         <a href="/terms" class="nav-link">
           <i class="fas fa-file-contract" aria-hidden="true"></i>
           <span>Terms</span>
         </a>
       </div>
     </div>
     <footer>
       &copy; {{ .Values.projectName }} - {{ now | date "2006" }}
     </footer>
     </main>
    </body>
    </html>

  robots.txt: |
    # Block Googlebot and Adsbot
    User-agent: Googlebot
    User-agent: AdsBot-Google
    Disallow: /

    # Block all crawlers except AdsBot (AdsBot crawlers must be named explicitly)
    User-agent: *
    Disallow: /

    Sitemap: https://www.{{ .Values.domain }}/sitemap.xml

  security.txt: |
    Contact: mailto:contact@{{ .Values.domain }}
    Expires: 2031-01-01T06:01:00.000Z
    Preferred-Languages: en
    Canonical: https://www.{{ .Values.domain }}/.well-known/security.txt

  sitemap.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
      <url>
        <loc>https://{{ .Values.domain }}/privacy</loc>
        <lastmod>2025-02-26-T15:53:44-06:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>1</priority>
      </url>
      <url>
        <loc>https://{{ .Values.domain }}/error401</loc>
        <lastmod>2025-02-26-T15:53:44-06:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>1</priority>
      </url>
      <url>
        <loc>https://{{ .Values.domain }}/error400</loc>
        <lastmod>2025-02-26-T15:53:44-06:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>1</priority>
      </url>
      <url>
        <loc>https://{{ .Values.domain }}</loc>
        <lastmod>2025-02-26-T15:53:44-06:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>1</priority>
      </url>
      <url>
        <loc>https://{{ .Values.domain }}/legal</loc>
        <lastmod>2025-02-26-T15:53:44-06:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>1</priority>
      </url>
      <url>
        <loc>https://{{ .Values.domain }}/error404</loc>
        <lastmod>2025-02-26-T15:53:44-06:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>1</priority>
      </url>
      <url>
        <loc>https://{{ .Values.domain }}/error500</loc>
        <lastmod>2025-02-26-T15:53:44-06:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>1</priority>
      </url>
    </urlset>

  error400.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>{{ .Values.projectName }}.com | Error 400</title>
      <link rel="icon" href="favicon.ico" type="image/png" />
      <link href="https://fonts.googleapis.com/css?family=Reem+Kufi|Roboto:300" rel="stylesheet">
      <link href="https://use.fontawesome.com/releases/v6.7.2/css/all.css" rel="stylesheet">
      <link rel="stylesheet" href="css/reset.css">
      <link rel="stylesheet" href="css/styles.css">
      <link rel="stylesheet" href="css/theme.css">
    </head>
    <body>
      <main>
        <div class="img-sm"><img src="logo.png" alt="{{ .Values.projectName }} Logo"></div>
        <div class="icons-apps">
          <a target="_self" href="{{ .Values.supportUrl }}">
            <i class="fa-solid fa-4" aria-hidden="false" title="4"></i>
            <span class="sr-only">5</span>
          </a>
          <a target="_self" href="{{ .Values.supportUrl }}">
            <i class="fa-solid fa-0" aria-hidden="false" title="0"></i>
            <span class="sr-only">0</span>
          </a>
          <a target="_self" href="{{ .Values.supportUrl }}">
            <i class="fa-solid fa-0" aria-hidden="false" title="0"></i>
            <span class="sr-only">0</span>
          </a>
        </div>
      </main>
    </body>
    </html>

  error401.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>{{ .Values.projectName }}.com | Error 401</title>
      <link rel="icon" href="favicon.ico" type="image/png" />
      <link href="https://fonts.googleapis.com/css?family=Reem+Kufi|Roboto:300" rel="stylesheet">
      <link href="https://use.fontawesome.com/releases/v6.7.2/css/all.css" rel="stylesheet">
      <link rel="stylesheet" href="css/reset.css">
      <link rel="stylesheet" href="css/styles.css">
      <link rel="stylesheet" href="css/theme.css">
    </head>
    <body>
      <main>
        <div class="img-sm"><img src="logo.png" alt="{{ .Values.projectName }} Logo"></div>
        <div class="icons-apps">
          <a target="_self" href="{{ .Values.supportUrl }}">
            <i class="fa-solid fa-4" aria-hidden="false" title="4"></i>
            <span class="sr-only">5</span>
          </a>
          <a target="_self" href="{{ .Values.supportUrl }}">
            <i class="fa-solid fa-0" aria-hidden="false" title="0"></i>
            <span class="sr-only">0</span>
          </a>
          <a target="_self" href="{{ .Values.supportUrl }}">
            <i class="fa-solid fa-1" aria-hidden="false" title="1"></i>
            <span class="sr-only">1</span>
          </a>
        </div>
      </main>
    </body>
    </html>

  error404.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>{{ .Values.projectName }}.com | Error 404</title>
      <link rel="icon" href="favicon.ico" type="image/png" />
      <link href="https://fonts.googleapis.com/css?family=Reem+Kufi|Roboto:300" rel="stylesheet">
      <link href="https://use.fontawesome.com/releases/v6.7.2/css/all.css" rel="stylesheet">
      <link rel="stylesheet" href="css/reset.css">
      <link rel="stylesheet" href="css/styles.css">
      <link rel="stylesheet" href="css/theme.css">
    </head>
    <body>
      <main>
        <div class="img-sm"><img src="logo.png" alt="{{ .Values.projectName }} Logo"></div>
        <div class="icons-apps">
          <a target="_self" href="{{ .Values.supportUrl }}">
            <i class="fa-solid fa-4" aria-hidden="false" title="4"></i>
            <span class="sr-only">5</span>
          </a>
          <a target="_self" href="{{ .Values.supportUrl }}">
            <i class="fa-solid fa-0" aria-hidden="false" title="0"></i>
            <span class="sr-only">0</span>
          </a>
          <a target="_self" href="{{ .Values.supportUrl }}">
            <i class="fa-solid fa-4" aria-hidden="false" title="4"></i>
            <span class="sr-only">0</span>
          </a>
        </div>
      </main>
    </body>
    </html>

  error500.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>{{ .Values.projectName }}.com | Error 500</title>
      <link rel="icon" href="favicon.ico" type="image/png" />
      <link href="https://fonts.googleapis.com/css?family=Reem+Kufi|Roboto:300" rel="stylesheet">
      <link href="https://use.fontawesome.com/releases/v6.7.2/css/all.css" rel="stylesheet">
      <link rel="stylesheet" href="css/reset.css">
      <link rel="stylesheet" href="css/styles.css">
      <link rel="stylesheet" href="css/theme.css">
    </head>
    <body>
      <main>
        <div class="img-sm"><img src="logo.png" alt="{{ .Values.projectName }} Logo"></div>
        <div class="icons-apps">
          <a target="_self" href="{{ .Values.supportUrl }}">
            <i class="fa-solid fa-5" aria-hidden="false" title="5"></i>
            <span class="sr-only">5</span>
          </a>
          <a target="_self" href="{{ .Values.supportUrl }}">
            <i class="fa-solid fa-0" aria-hidden="false" title="0"></i>
            <span class="sr-only">0</span>
          </a>
          <a target="_self" href="{{ .Values.supportUrl }}">
            <i class="fa-solid fa-0" aria-hidden="false" title="0"></i>
            <span class="sr-only">0</span>
          </a>
        </div>
      </main>
    </body>
    </html>
