---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apache.fullname" . }}-assets
  labels:
    {{- include "apache.labels" . | nindent 4 }}
binaryData:
  logo.png: {{ .Files.Get "logo.png.b64" | quote }}
  favicon.ico: {{ .Files.Get "favicon.ico.b64" | quote }}
