{{- if .Values.ingress.enabled -}}
---
# Apache Main IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "apache.fullname" . }}
  labels:
    {{- include "apache.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.domain }}`) || Host(`www.{{ .Values.domain }}`)
    kind: Rule
    services:
    - name: {{ include "apache.fullname" . }}
      port: {{ .Values.service.port }}
    middlewares:
    - name: {{ .Values.ingress.middleware }}
  tls:
    certResolver: {{ .Values.ingress.certResolver }}
---
# Apache Webfinger IngressRoute (higher priority)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "apache.fullname" . }}-webfinger
  labels:
    {{- include "apache.labels" . | nindent 4 }}
    route: webfinger
spec:
  entryPoints:
    - websecure
  routes:
  - match: (Host(`{{ .Values.domain }}`) || Host(`www.{{ .Values.domain }}`)) && PathPrefix(`/.well-known/webfinger`)
    kind: Rule
    priority: 100
    services:
    - name: {{ include "apache.fullname" . }}
      port: {{ .Values.service.port }}
  tls:
    certResolver: {{ .Values.ingress.certResolver }}
{{- end }}
