---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homer.fullname" . }}-config
  labels:
    {{- include "homer.labels" . | nindent 4 }}
data:
  config.yml: |
    ---
    title: "{{ .Values.config.title }}"
    subtitle: "{{ .Values.config.subtitle }}"
    logo: "{{ .Values.config.logo }}"
    footer: {{ .Values.config.footer }}

    theme: {{ .Values.config.theme }}

    defaults:
      colorTheme: auto

    connectivityCheck: {{ .Values.config.connectivityCheck }}

    colors:
      dark:
        highlight-primary: "#3367d6"
        highlight-secondary: "#4285f4"
        highlight-hover: "#5a95f5"
        background: "#485564"
        card-background: "#333c46"
        text: "#eaeaea"
        text-header: "#ffffff"
        text-title: "#fafafa"
        text-subtitle: "#f5f5f5"
        card-shadow: rgba(0, 0, 0, 0.4)
        link: "#3273dc"
        link-hover: "#ffdd57"

    links:
      - name: "Login"
        icon: "fas fa-user"
        url: "https://login.authoritah.com/"

    services:
      - name: "Media Tools"
        icon: "fas fa-toolbox"
        items:
          - name: "Seerr"
            subtitle: "User Friendly Media Request Tool"
            url: "https://request.{{ .Values.media_tld }}/"
            tag: "Request"
          - name: "Suggestarr"
            subtitle: "Media Suggestions + Recommendations"
            url: "https://suggestarr.authoritah.com/"
            tag: "Discovery"
          - name: "Wizarr"
            subtitle: "Manage Plex Invites"
            url: "https://join.{{ .Values.media_tld }}/"
            tag: "Access"
          - name: "Bazarr"
            subtitle: "Manage + Download Subtitles"
            url: "https://bazarr.authoritah.com/"
            tag: "Subtitles"
          - name: "Lidatube"
            subtitle: "YouTube to Lidarr Integration"
            url: "https://lidatube.authoritah.com/"
            tag: "Music"
          - name: "Tdarr"
            subtitle: "Library Analytics + Transcode Automation"
            url: "https://tdarr.authoritah.com/"
            tag: "Processing"
          - name: "Tautulli"
            subtitle: "Monitor Plex Media Server"
            url: "https://stats.{{ .Values.media_tld }}/"
            tag: "Monitoring"
          - name: "Watchstate"
            subtitle: "Sync Watch State Across Media Servers"
            url: "https://watchstate.authoritah.com/"
            tag: "Sync"

      - name: "Content Management"
        icon: "fas fa-tasks"
        items:
          - name: "Sonarr"
            subtitle: "TV Show PVR for Usenet + BitTorrent"
            url: "https://sonarr.authoritah.com/"
            tag: "TV"
          - name: "Sonarr 4K"
            subtitle: "4K TV PVR for Usenet + BitTorrent"
            url: "https://sonarr3.authoritah.com/"
            tag: "UHD"
          - name: "Sonarr Anime"
            subtitle: "Anime PVR for Usenet + BitTorrent"
            url: "https://sonarr2.authoritah.com/"
            tag: "Anime"
          - name: "Radarr"
            subtitle: "Movie PVR for Usenet + BitTorrent"
            url: "https://radarr.authoritah.com/"
            tag: "Movies"
          - name: "Radarr 4K"
            subtitle: "4K Movie PVR for Usenet + BitTorrent"
            url: "https://radarr2.authoritah.com/"
            tag: "UHD"
          - name: "Lidarr"
            subtitle: "Music PVR for Usenet + BitTorrent"
            url: "https://lidarr.authoritah.com/"
            tag: "Music"
          - name: "Listenarr"
            subtitle: "Audiobook Manager for Usenet + BitTorrent"
            url: "https://listenarr.authoritah.com/"
            tag: "Audiobook"
          - name: "Sportarr"
            subtitle: "Sports Content Manager"
            url: "https://sportarr.authoritah.com/"
            tag: "Sports"

      - name: "Tools"
        icon: "fa-solid fa-screwdriver-wrench"
        items:
          - name: "Unifi"
            subtitle: "Unifi Site Manager Dashboard"
            url: "https://unifi.ui.com/"
            tag: "Firewall"
          - name: "Traefik"
            subtitle: "Open Source Edge Router"
            url: "https://api.authoritah.com/"
            tag: "Router"
          - name: "ArgoCD"
            subtitle: "GitOps Continuous Delivery"
            url: "https://cd.authoritah.com/"
            tag: "GitOps"
          - name: "Grafana"
            subtitle: "Analytics & Monitoring Platform"
            url: "https://grafana.authoritah.com/"
            tag: "Metrics"
          - name: "Prometheus"
            subtitle: "Monitoring System & Time Series Database"
            url: "https://metrics.authoritah.com/"
            tag: "Metrics"
          - name: "Gitea"
            subtitle: "Lightweight DevOps Platform"
            url: "https://{{ .Values.git_tld }}/"
            tag: "Git"
          - name: "IT Tools"
            subtitle: "Handy Online Tools for Developers"
            url: "https://tools.authoritah.com/"
          - name: "13ft"
            subtitle: "Remove Popups, Banners + Ads"
            url: "https://13ft.{{ .Values.link_tld }}/"

      - name: "Storage"
        icon: "fas fa-database"
        items:
          - name: "Karakeeper"
            subtitle: "Save + Classify Articles"
            url: "https://{{ .Values.click_tld }}/"
            tag: "Bookmarks"
          - name: "Immich"
            subtitle: "Browse, Organize & Share Photos"
            url: "https://{{ .Values.photo_tld }}/"
            tag: "Photos"
          - name: "Proxmox"
            subtitle: "Virtualization & Container Platform"
            url: "https://pve.authoritah.com/"
            tag: "Security"
          - name: "Paperless"
            subtitle: "Browse & Scan Documents"
            url: "https://docs.authoritah.com/"
            tag: "Documents"
          - name: "Paperless AI"
            subtitle: "Automated Document Analyzer"
            url: "https://ai.authoritah.com/"

      - name: "Downloads & Indexing"
        icon: "fas fa-download"
        items:
          - name: "Prowlarr"
            subtitle: "Indexer for Torrent + Usenet"
            url: "https://prowlarr.authoritah.com/"
            tag: "Indexer"
          - name: "Autobrr"
            subtitle: "Modern Download Automation"
            url: "https://autobrr.authoritah.com/"
            tag: "Automation"
          - name: "SABnzbd"
            subtitle: "Easy Binary Newsreader"
            url: "https://sabnzbd.authoritah.com/"
            tag: "Usenet"
          - name: "Transmission"
            subtitle: "Cross-Platform BitTorrent client"
            url: "https://transmission.authoritah.com/"
            tag: "Torrents"

      - name: "Streaming"
        icon: "fas fa-play-circle"
        items:
          - name: "Plex"
            subtitle: "Managing + Streaming Media"
            tag: "Video"
            url: "https://{{ .Values.media_tld }}/"
          - name: "Jellyfin"
            subtitle: "Free Media System"
            tag: "Video"
            url: "https://jellyfin.authoritah.com/"
          - name: "Kavita"
            subtitle: "Fast + Cross Platform Reading Server"
            tag: "eReader"
            url: "https://kavita.authoritah.com/"
