---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex
  namespace: default
  labels:
    app: plex
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`plex.authoritah.com`)
    kind: Rule
    services:
    - name: plex
      port: 32400
  tls:
    certResolver: dnschallenge
